version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: articles-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: articles_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - articles-network

volumes:
  mongodb_data:
    driver: local

networks:
  articles-network:
    driver: bridge

